### PR TITLE
fix inversion issue

### PR DESCRIPTION
**Pull request by jglatts**
fixing the inversion issue

### CODE REVIEW

**Review by Abejaved — DISMISSED** [review]
Maginificent

**Review by tuj52977 — CHANGES_REQUESTED** [review]
Code works but fix syntax

**Comment by jglatts** [comment]
gothcu

**Comment by Abejaved** [comment]
Looks good now

**Review by lewiswinnemore — APPROVED** [review]

**Review by tuj52977 — APPROVED** [review]

**Pull request merged**
